# fly.toml file generated for market-data-666 on 2023-04-03T22:45:55-03:00

app = "cool-bush-3230"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
